### ISSUE TITLE
Content rendering error in MDN docsets

### ISSUE THREAD

**Issue by dania-prog** [zealdocs/zeal#1155]
After updating to zeal 0.6.1, the content could not be displayed in the Tabs. Pasted below  is the display error.
![image](https://user-images.githubusercontent.com/52634550/68454947-71262b00-01fa-11ea-903d-4d00eeacbb39.png)
kindly assist to resolve. Thanks

**Comment by sanruby** [comment]
error same as , the javascript docset

**Comment by mansur-r** [comment]
Same error, using just an initial html docset

**Comment by antoni-minkiewicz** [comment]
Same error

**Comment by falegh** [comment]
Zeal 0.6.0, Ubuntu 18.04

`Content rendering error` after installing updates to these docsets:
- CSS
- HTML
- JavaScript
- SVG

React, Bash and some others working fine

**Comment by dania-prog** [comment]
The following docsets has the error (content rendering error) after installing updates to the docsets:

- CSS
- HTML
- JS
- Java SE11 (the application closes out)
- Java SE9 (the application closes out)
- Perl
- RubyMotion
- SVG
- WordPress
The rest are functional. Kindly lets know when it has been resolved.

**Comment by trollixx** [comment]
Docsets produced from MDN (HTML, CSS, JS, SVG) are broken because of the new JS functionality. It appears to be fixed by the https://github.com/mdn/kuma/pull/5996. Unfortunately, WebKit (and also Firefox) can't load polyfills over the `file:` scheme. I'm looking into possible solutions.

@dania-prog I cannot reproduce crashes with the Java docsets. Is it possible that you are affected by https://github.com/zealdocs/zeal/issues/868?

Perl and RubyMotion docsets didn't have index page set, should be fixed now. Refresh the docset list, and reinstall the docsets.

The WordPress docset has incorrect `dashIndexFilePath` in `Info.plist`, `no_index_test/index.html` doesn't exist. @Kapeli can you take a look? I think the property is redundant because `index.html` is present.

**Comment by Kapeli** [comment]
I sometimes set the `dashIndexFilePath` to inexistent pages to make Dash not show an index for the docset anymore. In a future version of Dash index pages won't be as important anymore, so some docsets won't have them anymore.

**Comment by zjffun** [comment]
it can fix temporary by remove the
`CSS.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.ddbbd86b0685.js`.

**Comment by prurigro** [comment]
Nice fix zjiffun-- here's the same solution turned into a little function you can add to your .bashrc that'll fix all the docs with that problem:

```bash
zeal-docs-fix() {
    pushd "$HOME/.local/share/Zeal/Zeal/docsets" >/dev/null || return
    find . -iname 'react-main*.js' -exec rm '{}' \;
    popd >/dev/null || exit
}
```

**Comment by trollixx** [comment]
> I sometimes set the dashIndexFilePath to inexistent pages to make Dash not show an index for the docset anymore. In a future version of Dash index pages won't be as important anymore, so some docsets won't have them anymore.

@Kapeli what does Dash show in such scenario?

**Comment by Kapeli** [comment]
The current version of Dash shows a home page that looks like this:

<img width="464" alt="Screenshot 2019-11-15 at 06 33 35" src="https://user-images.githubusercontent.com/1445635/68917189-df766a80-0771-11ea-8f95-e7929d640664.png">

**Comment by trollixx** [comment]
So Dash simply displays it own home page instead of docset's index page?

**Comment by Kapeli** [comment]
Yes, but only when there's no docset index page. Otherwise, it shows the index page.

Future version of Dash will have a "Show index page" option which the user will have to press specifically (something like how it works on Dash for iOS). For docsets without an index page, I won't show that option.

**Comment by trollixx** [comment]
Unfortunately, serving MDN docset from a local HTTP server doesn't help. I think even with the polyfills Qt WebKit is just too old, while for example Firefox began to render properly.

Reported Qt WebKit problem in https://github.com/qtwebkit/qtwebkit/issues/922.

Considering the amount of issues with Qt WebKit, at this point it seems like attempting another migration to Qt WebEngine. There is also [a pending PR](https://github.com/zealdocs/zeal/pull/1125).

**Comment by stompy-chum** [comment]
@trollixx: Chrome and Chromium have a command-line flag to enable local file serving, in case that's useful:

chrome.exe --allow-file-access-from-files

I use this to test HTML Imports locally, for example.

**Comment by swedishpotato** [comment]
Is there any view yet on when this might be fixed? We love Zeal and depend on it for serving docsets in a completely offline teaching environment, but since the last docset updates we've lost HTML, CSS, JS etc docsets. Is there any way of getting the old docsets back in the meantime so that we at least have something we can use?

**Comment by madand** [comment]
@swedishpotato if you have access to any Unix-like OS with Shell (GNU/Linux, MacOSX, *BSD), see https://github.com/zealdocs/zeal/issues/1155#issuecomment-553213420 for easy fix of the docsets.

If you only have Windows, you can manually clean-up the relevant docsets by deleting the offending JS file from each docset's folder:
* `JavaScript.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.e49be9481ede.js`
* `CSS.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.e49be9481ede.js`
* `HTML.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.e49be9481ede.js`

The exact JS filename may differ in that `e49be9481ede` bit, just look for `react-main.<something>.js` and delete it.

**Comment by jimmylab** [comment]
> @swedishpotato if you have access to any Unix-like OS with Shell (GNU/Linux, MacOSX, *BSD), see [#1155 (comment)](https://github.com/zealdocs/zeal/issues/1155#issuecomment-553213420) for easy fix of the docsets.
> 
> If you only have Windows, you can manually clean-up the relevant docsets by deleting the offending JS file from each docset's folder:
> 
> * `JavaScript.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.e49be9481ede.js`
> * `CSS.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.e49be9481ede.js`
> * `HTML.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.e49be9481ede.js`
> 
> The exact JS filename may differ in that `e49be9481ede` bit, just look for `react-main.<something>.js` and delete it.

Much thanks for your tips!

Here is my batch version:
:: set you own doc path
set DOCPATH=C:\ZealDocs

set CORRUPT_FILE=Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.*.js
ren "%DOCPATH%\JavaScript.docset\%CORRUPT_FILE%" *.js.bak
ren "%DOCPATH%\CSS.docset\%CORRUPT_FILE%" *.js.bak
ren "%DOCPATH%\HTML.docset\%CORRUPT_FILE%" *.js.bak
ren "%DOCPATH%\SVG.docset\%CORRUPT_FILE%" *.js.bak
pause

**Comment by tonnysi** [comment]
Only add slash before %CORRUPT_FILE%

```:: set you own doc path
set DOCPATH=C:\ZealDocs
 
set CORRUPT_FILE=Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.*.js
ren "%DOCPATH%\JavaScript.docset\%CORRUPT_FILE%" *.js.bak
ren "%DOCPATH%\CSS.docset\%CORRUPT_FILE%" *.js.bak
ren "%DOCPATH%\HTML.docset\%CORRUPT_FILE%" *.js.bak
ren "%DOCPATH%\SVG.docset\%CORRUPT_FILE%" *.js.bak
pause
```

**Comment by jimmylab** [comment]
@tonnysi Thanks!

**Comment by dania-prog** [comment]
@zjffun @madand thanks a bunch

**Comment by madand** [comment]
@dania-prog you're welcome. But you better re-open the issue, since we only found a workaround and there is no solution on Zeal side yet. More people will become affected as they will update docsets and they will have much easier time searching for the workaround among the open issues.

**Comment by AdrianoFerrari** [comment]
I second the request to re-open, as the workaround doesn't even work for me (Xubuntu 19.10, latest Zeal).

**Comment by peethaxgit** [comment]
I have got the same problem here, any solution yet?

**Comment by jeroentbt** [comment]
@peethaxgit no solution but a workaround can be found just a few comments up.
(remove 'react-main*.js from the offending docsets)

**Comment by santimirandarp** [comment]
im running zeal on lubuntu, added 

zeal-docs-fix() {
    pushd "$HOME/.local/share/Zeal/Zeal/docsets" >/dev/null || return
    find . -iname 'react-main*.js' -exec rm '{}' \;
    popd >/dev/null || exit
}

to the .bashrc file and keeps returning  the Content rendering error

Any ideas?  :(

**Comment by jeroentbt** [comment]
@santimirandarp have you opened a new terminal and restarted Zeal afterwards?
what does `find $HOME/.local/share/Zeal/Zeal/docsets -iname 'react-main*.js'` return?

**Comment by santimirandarp** [comment]
> @santimirandarp have you opened a new terminal and restarted Zeal afterwards?
> what does `find $HOME/.local/share/Zeal/Zeal/docsets -iname 'react-main*.js'` return?

I think I did both restarting terminal, using source, restart zeal, but I'm not sure now. Removing the file worked perfectly...

**Comment by diegofelipece** [comment]
Quick fix (same commented before):
``` bash
find ~/.local/share/Zeal/Zeal/docsets -name "react-main.*.js" -exec rm -rf {} \;
```
This will remove all "react-main.*.js" files from all docsets and probably need to be done again after updates.

If you prefer, you can remove the `-exec rm -rf {} \;` part, to see the list of files without deleting then.

**Comment by awencheww** [comment]
> After updating to zeal 0.6.1, the content could not be displayed in the Tabs. Pasted below is the display error.
> ![image](https://user-images.githubusercontent.com/52634550/68454947-71262b00-01fa-11ea-903d-4d00eeacbb39.png)
> kindly assist to resolve. Thanks

Find react-main.*.js file then rename it and delete the extension name after "react-main." that would be fixed the issue, I'm using zeal in ubuntu 18.04.
![Screenshot from 2020-01-18 21-01-46](https://user-images.githubusercontent.com/12206797/72664185-cc17a200-3a35-11ea-934e-6de42709aa1a.png)

**Comment by JonDevOps** [comment]
Has this been fixed yet? I'm having the same issue on the version before .61 after updating the docsets.

**Comment by jeroentbt** [comment]
@JonDevOps The issue is still open. It has not been fixed.
You can make the docsets work again by applying the workaround that has been described multiple times in the thread above.

**Comment by trollixx** [comment]
The fix depends on the next Qt WebKit release, see https://github.com/qtwebkit/qtwebkit/issues/922 linked above.

**Comment by JonDevOps** [comment]
@trollixx is this problem being caused because mdn is switching to react? I noticed awhile ago I couldnt even save the Django pages in the Learn Web Development section offline because I would basically get the same error.

**Comment by trollixx** [comment]
@JonDevOps yes, and the fact that Qt WebKit is still based on the very old version of WebKit, but I hope that will be addressed soon.

**Comment by JonDevOps** [comment]
I wish MDN would just make their content downloadable already. Anyway, if there is anything I can do to help with Zeal please keep me in the loop. Thanks for the feedback!

**Comment by trollixx** [comment]
You can give https://kapeli.com/mdn_offline a try.

**Comment by JonDevOps** [comment]
Surprisingly I got a application render error from the docs there as well. Luckily I have all the learn web development sections for JavaScript saved from March of 2019(If anyone wants them let me know and Ill upload them to a repo.). I guess the best we can do now besides the workaround mentioned above is to save the webpages as an image with something like the "easy screenshot" browser extension. At least until we figure out the next steps at MDN or here at Zeal.

**Comment by yvesdaxmaz** [comment]
I'm on ubuntu 18.04 and I got the same issue with CSS and HTML Docsets.  to solve It I just move the file which is listing in **Browser Inspecter** Console after I click on the **Open Page In Desktop Browsser**  which apear after right click on the error page. 

.local/share/Zeal/Zeal/docsets/HTML.docset/Contents/Resources/Documents/developer.mozilla.org/static/build/js/react-main.38db06bb67df.js:2 

after I move the file everything work perfectly, It work for both CSS and HTML

**Comment by meatnordrink** [comment]
Because this is still an issue, and because some of the solutions above work better than others, I'm going to post the solution, for Ubuntu 19.10, here: 

1. Go to `.local/share/zeal` in Nautilus/Dolphin/CLI/whatever. 
2. Find all files that begin with `react-main`. There should be three. They will have names like: 
  `react-main.7283hcsd93782ls.js`
3. One may be slightly larger than the others; select it, and rename it `react-main.js`. 
4. Delete the other two. 

Thanks to Zeal for being a great tool!

**Comment by kvn1351** [comment]
This only fixes the local docs however. Couldn't Zeal just drop those js files altogether? That way it would work for online docs too.

**Comment by carestad** [comment]
Is there any way to automate this in Linux so it is done when updating my docsets?

**Comment by meatnordrink** [comment]
> Is there any way to automate this in Linux so it is done when I update my docsets?

@carestad , if you check out @prurigro 's solution, above - https://github.com/zealdocs/zeal/issues/1155#issuecomment-553213420

They've written a function you can put in your `.bashrc`. I haven't tried it myself, but it has a fair number of upvotes.

**Comment by buckle2000** [comment]
I am surprised that this is still not fixed.

**Comment by Kwaadpepper** [comment]
this worked for me https://github.com/zealdocs/zeal/issues/1155#issuecomment-553213420
I just pasted in terminal :skull:

**Comment by data-man** [comment]
Fixed by #1125.
For CSS, HTML, JavaScript and SVG docsets at least. :100:

**Comment by sscohn** [comment]
It's so hard to find information about specific problems such as these. I really don't know why. It's a Google search engine thing, I guess. The search wording has to be just right. Anyhow, yes, I'm glad to have found this web page confirming they debugging I just completed, because I was about to become hopping mad at Mozilla of whom I was suspecting had finally engaged in Microsoft-type tactics by blocking access to MDN because my Firefox browser was too old! (Firefox 43 is not THAT old -- it works just fine.) Anyhow, while trying to view any MDN page other than the home page, they would not render and the Firefox window would be blank. So I rolled up my sleeves, copied one of the doc pages, procured all the CSS and JS files that went with it, changed the URLs so they'd be local, and crossed my fingers that debugging the page wouldn't take all night! Luckily, within an hour, yep, I narrowed it down to one javascript file: react-main.f09071cb3cf6.js. Well, whadya know! That's what all you commentators have been talking about. Good. So it's messing stuff up. And so then it sounds like this phenomenon of non-rendering will be temporary.

Anyhow, as is typical, this "zeal" and "react" stuff is unfamiliar to me. I could look it all up -- or not! All I hope is that it doesn't interfere with my browsing with Firefox!

BTW: The react-main.js file didn't seem to deter Internet Explorer 11, which is very untypical of that browser! All IE versions since IE6 have been so flaky, they always have rendering troubles. Maybe this time it decided to ignore the react-main.js file. It rendered all MDN pages just fine. That's a switch!

**Comment by buckle2000** [comment]
It really doesn't work on FF 43. @sscohn I don't think Mozilla is aware of this. Do you mind reporting this to them?

**Comment by sscohn** [comment]
Thanks for the notice, but I need clarification. Do you mean to say that 
this new format/protocol software "react" INTENTIONALLY was designed to 
NOT work with slightly older Firefox versions, and that this react 
software is here to stay? That's what it sounds like you're saying. If 
so, that contradicts what reactions I read by MDN participants on the 
github.com/zealdocs/zeal/issues/1155 web page that I examined, because 
everyone who commented were talking about dumping the react-main.js file 
because it was causing all of them to not to be able to access MDN web 
pages.

You know, the truth is that I won't lose sleep over not being able to 
access MDN web pages without upgrading my browser becausse I really 
don't use that website very often and I could manage just as well 
without it. It would be a major loss, Still, all I can say is why keep 
fixin' stuff that ain't broke!? The MDN website worked just fine two 
months ago! I mean -- what's with THAT!? I don't want to get started 
about upgrades -- 'cause I could go on and on -- but suffice it to say 
that at this point in my life, I have no intention of upgrading Windows, 
my hardware or any other software -- EVER -- so long as I live. I've had 
enough. The software industry seems BENT on making sure that successive 
iterations of their software are completely backwards INCOMPATIBLE with 
previous versions -- a choice they make that is completely unnecessary, 
I might add. So, besides all the other arguments against that standard 
operating practice the software industry is bent on following, the 
master opposing argument trumping all other arguments is that nowadays, 
computers, the operating systems thay run on and the software 
applications that go along with all that is not really optional anymore 
-- it's like the 20th century necessity of the telephone, and so, then, 
since we all have to use this stuff, software users like myself find 
themselves at the mercy of the industry which dictates what we use and 
how we use it. Never mind that a vast majority of that software is 
"free"! (Or is it REALLY free?) That doesn't give software companies 
license to abuse their users.

My point is that computer users have no choices -- other than "take it 
or leave it". It's not like that in any other capitalistic industry! 
Consumers have choice of brands, makes, models and so forth. Naturally, 
as is the tendency of some capitalists, some industries afford consumers 
fewer choices than others. But the software industry has got a choke 
hold on society and has become a monstrous dictatorship. And that's 
gotta change -- and it will -- sooner or late -- but eventually, because 
all things must pass.

**Comment by trollixx** [comment]
@sscohn Zeal has no connection to either Mozilla or MDN. If you have issues with either, please use their respective bug trackers.

Speaking of Zeal, code in the master branch has been ported to Qt WebEngine, and that resolved all known rendering bugs. There are a few regressions which need to be addressed before v0.7.0 can be released, but the impatient can either give CI builds a try, or compile Zeal themselves.

**Comment by buckle2000** [comment]
I feel philosophical.

**Comment by andreaskern** [comment]
I ran into this issue today,
I failed to build the master branch (because of some qt5webengine -> gl.h issues)
As I use the fish shell I had to escape the curly braces in the script from https://github.com/zealdocs/zeal/issues/1155#issuecomment-574627330

```sh
find ~/.local/share/Zeal/Zeal/docsets -name "react-main.*.js" -exec rm --interactive \{\} \;
```

it now asks before deleting the files too.

**Comment by sdanielch** [comment]
https://github.com/zealdocs/zeal/issues/1155#issuecomment-642579981
Perfect solution on Ubuntu 20.04 
(find ~/.local/share/Zeal/Zeal/docsets -name "react-main.*.js" -exec rm --interactive \{\} \;
)
Thanks!!

**Comment by anibalsanchez** [comment]
A small tweak:

```sh
find ~/.local/share/Zeal/Zeal/docsets -name "react-main.*.js" -exec rm --interactive {} \;
```

**Comment by stemry83** [comment]
@anibalsanchez  Building on top:

If you're on Windows, has Git for Windows, using the default docset storage directory (``C:\Users\UserName\AppData\Local\Zeal\Zeal\docsets``), then run this script:

``
find ~/AppData/Local/Zeal/Zeal/docsets -name "react-main.*.js" -exec rm --interactive {} \;
``

Press `Enter` a few times to confirm the deletions.

**Comment by dblandin** [comment]
It took a bit of hunting to find where docsets are installed for a Flatpak-installed setup :

```
~/.var/app/org.zealdocs.Zeal/data/Zeal/Zeal/docsets
```

Here's an invocation building off of other comments to clean out these problematic JavaScript files within the docsets:

```
$ find .var/app/org.zealdocs.Zeal/data/Zeal/Zeal/docsets -name "react-main.*.js" -exec rm {} \;
```

source: https://docs.flatpak.org/en/latest/sandbox-permissions.html

**Comment by J3RN** [comment]
Now that this issue is resolved, would it be possible to cut a new release? I'm assuming the package maintainers for the assorted Linux distros (and Flatpak) are watching for a new tagged version to be released before packaging and distributing it.

**Comment by 2bit-hack** [comment]
[#1155 (comment)](https://github.com/zealdocs/zeal/issues/1155#issuecomment-574627330) fixed the rendering issue and displays the front page for the JavaScript docset, but whenever I click on any of the other links, I get a `QtNetworkError 203`.

The exact error is as follows:
`Error opening /home/sierrakilo/.local/share/Zeal/Zeal/docsets/JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval.html: No such file or directory`

This is because the path that was created on my device was `.../Global_objects/...` instead of `.../Global_Objects/...`. I fixed it by manually changing the directory name, but it would be nice if this was changed automatically.

I'm using Manjaro Linux KDE, and installed Zeal using pacman. Also, I can confirm this happened only for the JavaScript docset and not the HTML and CSS docsets.

**Comment by Zaggar** [comment]
If you are using Windows, i think this is more straight forward. 


https://www.programmersought.com/article/89484147811/

**Comment by lesar** [comment]
same problem running on Ubuntu 20.04 64bit desktop on rpi4

**Comment by gartun** [comment]
After removing (manually--Windows 10) that react.main file, only CSS docs are being displayed without a problem. HTML and JS docs are still buggy.

**Comment by Zaggar** [comment]
Then you will have to do same (delete the react-mainxxxxxx.js files)  for both  HTML.docset and JavaScript.docset

**Comment by gartun** [comment]
@Zaggar 

I forgot to mention that I'd deleted them all... It only works for CSS docs...

**Comment by sgrubsmyon** [comment]
> same problem running on Ubuntu 20.04 64bit desktop on rpi4
> 
> way the issue is closed if the problem persist?

Because, as @trollixx commented [on May 5](https://github.com/zealdocs/zeal/issues/1155#issuecomment-623863867), the issue has been fixed by the port to Qt WebEngine. It just has not been released yet and will enter release v0.7.0. Until that is out, you need to either compile Zeal yourself, try the CI builds or apply [the workaround](https://github.com/zealdocs/zeal/issues/1155#issuecomment-646006987).

**Comment by akx** [comment]
On Windows, you can use `del /s` (making it recursive), e.g.

```
C:\Users\yourusername\AppData\Local\Zeal\Zeal\docsets>del /s/q react-main*js
```

to find and eradicate the react-main.js files.

**Comment by kirillgalchevsky** [comment]
have the same problem with zeal 0.6.1, I cant see javascript, html, css

**Comment by marui888** [comment]
> 
> 
> I find it can fix temporary by remove the
> `CSS.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.ddbbd86b0685.js`.
It works, really

**Comment by thefonso** [comment]
This is broken again. Javascript, css, html docset from mdn are all dark. all other docsets display fine.

![](https://i.imgur.com/dh7UImZ.png)
