### ISSUE TITLE
Oracle JDK causes Zeal to crash on Arch Linux

### ISSUE THREAD

**Issue by voidliududu** [zealdocs/zeal#802]
My zeal is runing on manjaro linux, when I try to open a docset ,it exited.The log in terminal is as follows:

*** Error in `zeal': free(): invalid pointer: 0x00007fcb78fd33c0 ***
[1]    1887 abort (core dumped)  zeal

**Comment by SyrakuShaikh** [comment]
Same problem here, when I tried to open 'Docker' docset, Zeal crashed.

```
*** Error in `zeal': free(): invalid pointer: 0x00007f10d47d23c0 ***
[1]    16451 abort (core dumped)
```

detailed info:

```
$ coredumpctl info 16451
           PID: 16451 (zeal)
           UID: 1000 (shaikh)
           GID: 1000 (shaikh)
        Signal: 6 (ABRT)
     Timestamp: Sat 2017-10-21 15:37:05 CST (3min 0s ago)
  Command Line: zeal log.txt
    Executable: /usr/bin/zeal
 Control Group: /user.slice/user-1000.slice/session-c3.scope
          Unit: session-c3.scope
         Slice: user-1000.slice
       Session: c3
     Owner UID: 1000 (shaikh)
       Boot ID: 55f2ff28096149e58f155d225bb29454
    Machine ID: 26f090b164cf43619ddb4a3c9c38ae60
      Hostname: ArchX
       Storage: /var/lib/systemd/coredump/core.zeal.1000.55f2ff28096149e58f155d225bb29454.16451.1508571425000000.lz4
       Message: Process 16451 (zeal) of user 1000 dumped core.
                
                Stack trace of thread 16451:
                #0  0x00007f1157f3c8a0 raise (libc.so.6)
                #1  0x00007f1157f3df09 abort (libc.so.6)
                #2  0x00007f1157f7f517 __libc_message (libc.so.6)
                #3  0x00007f1157f85c84 malloc_printerr (libc.so.6)
                #4  0x00007f1157f87599 _int_free (libc.so.6)
                #5  0x00007f10d4558282 _ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE (libdeploy.so)
                #6  0x00007f10d4564de3 _ZNSt6locale5_ImplC2Em (libdeploy.so)
                #7  0x00007f10d4565d55 _ZNSt6locale18_S_initialize_onceEv (libdeploy.so)
                #8  0x00007f1156281dbf __pthread_once_slow (libpthread.so.0)
                #9  0x00007f10d4565da1 _ZNSt6locale13_S_initializeEv (libdeploy.so)
                #10 0x00007f10d4565de3 _ZNSt6localeC1Ev (libdeploy.so)
                #11 0x00007f10d45376a4 _ZNSt8ios_base4InitC1Ev (libdeploy.so)
                #12 0x00007f10d452f7b8 _Z41__static_initialization_and_destruction_0ii (libdeploy.so)
                #13 0x00007f10d452f7ea _GLOBAL__sub_I_JLIWrapper_md.cpp (libdeploy.so)
                #14 0x00007f115e3f457a n/a (n/a)
```

**Comment by SyrakuShaikh** [comment]
BTW, another app `golendict` in my computer encountered a very similar problem.

```
*** Error in `goldendict': free(): invalid pointer: 0x00007.... ***
[1]    16... abort (core dumped)
```

My OS: archlinux
- gcc 7.2.0 
- glibc 2.26-5
- qt5-base 5.9.2-1
- qt5-webengine 5.9.2-1
- qt5-webkit 5.212.0alpha2-5


It seems that these problems are related to some libraries of the system? I'm not an expert, just some thoughts here.

**Comment by trollixx** [comment]
What do you mean by "open a docset"? Clicking on it in the tree on the left? Could be a Qt WebKit bug, but I don't see it in your stack trace...

**Comment by SyrakuShaikh** [comment]
Yeah, I mean clicking on the docset in the tree on the left.
It could be a Qt bug. I'll try some downgrades of these qt5 packages for tests.

**Comment by SyrakuShaikh** [comment]
I downgrade:

1. qt5-webkit (5.212.0alpha2-5 -> 5.9.0-1)
2. qt5-imageformats (5.9.2-1 -> 5.9.0-1)
3. qt5-x11extras (5.9.2-1 -> 5.9.0-1)
4. qt5-webengine  5.9.2-1 ->  5.9.0-2

and recompile `aur/zeal-git`.

**Docker** docset turns to be normal; **julia**, **pandas**, **matplotlib** still crash.

**Comment by SyrakuShaikh** [comment]
Further tests show that just downgrading one package 
```
qt5-webkit (5.212.0alpha2-5 => 5.8.0-3)
```
can fix this problem. **Zeal** works great now.

**Comment by eppdev** [comment]
the same problem with me, and i'm using archlinux, so I cannot downgrade my system

**Comment by SyrakuShaikh** [comment]
@eppdev Maybe you need a package **downgrade** in AUR. After installing it, you can downgrade `qt5-webkit` to fix this problem.

**Comment by trollixx** [comment]
Appears to be specific to Arch Linux. Most likely linking issues in `qt5-webkit`. #807 also has a very strange stack trace.

@Barthalion could you take a look?

**Comment by eppdev** [comment]
@SyrakuShaikh, @trollixx : I downgrade qt5-webkit to 5.8.0, and the problem is solved! thx a lot.

**Comment by SyrakuShaikh** [comment]
I just tested a new version of `qt5-webkit` **5.212.0alpha2-6**,  `Zeal` crashed. So, for now, need to stay with the **5.8.0** version.

**Comment by ppwwyyxx** [comment]
Same here. Archlinux as well. 5.9.0 doesn't work, and downgrading to qt5-webkit-5.8.0-3 can solve the problem.

**Comment by ivoshm** [comment]
I'm using **qt5-webkit-5.9.0-1** on Manjaro and it works.

**Comment by Barthalion** [comment]
Sorry folks, I'm traveling till the next week. @antonio-rojas, can you look at it?

@ivoshm: Only by sheer luck, as in 80% Manjaro is `Arch - x weeks`.

**Comment by antonio-rojas** [comment]
This is caused by (Oracle) Java 9 when QtWebKit tries to load its plugin (no idea how or why). See https://bbs.archlinux.org/viewtopic.php?id=231222 for more info. Note that Arch doesn't support Oracle Java, only OpenJDK.

**Comment by trollixx** [comment]
@annulen any idea why would Qt WebKit try to load some Java library? Sounds like a regression in 5.212 since reverting solves the problem. Or could be also something Arch specific.

**Comment by annulen** [comment]
Does this JVM installation provide NPAPI plugin?

It can be that both QtWebKit versions load that file but only in 5.212 it leads to crash.

It would be interesting to see output of gdb command `info sharedlibrary` after crash

**Comment by ivoshm** [comment]
@Barthalion No,no ... I downgraded - on Manjaro is crashing 5.212.0alpha2-6 now. But downgrade to 5.9.0 was enough.

@annulen You right - it' Oracle Java 9 ... look at last lines of included "sharedlib" trace in [qt5web-crash.txt](https://github.com/zealdocs/zeal/files/1429748/qt5web-crash.txt).

After uninstalling Oracle JDK 9 problem disappeared, after reinstalling is back.

**Comment by ivoshm** [comment]
Future investigation: AUR version of JDK 9 installs in /usr/lib/mozilla/plugins link to libnpjp2-jdk9.so. If you remove it (who needs Java in browser this days) - zeal works.

**Comment by annulen** [comment]
It seems you have 2 Java plugins loaded at the same time:

/usr/lib/jvm/java-7-jdk/jre/lib/amd64/libnpjp2.so
/usr/lib/jvm/java-9-jdk/lib/libnpjp2.so

This may be a source of trouble

**Comment by ivoshm** [comment]
@annulen No, it's directly Oracle JDK9 ... I try uninstall another JDKs on my machine and problem stays.

**Comment by eppdev** [comment]
That's the problem between the latest qt5-webkit and oracle jdk9, I have openjdk8、openjdk9 and oracle jdk9, and the problem is solved when I uninstall oracle jdk9

**Comment by eppdev** [comment]
I tried qt5-webkit 5.212.0alpha2-7， the problem still exists.

**Comment by SyrakuShaikh** [comment]
@eppdev I replaced `Oracle JDK` with `Open JDK` and then update `qt5-webkit` to the latest, the problem is fixed. Maybe you could have a try.

**Comment by Shihira** [comment]
Replacing Oracle JDK fixed the problem on my Arch.

**Comment by alireza6677** [comment]
Removing `Oracle jdk` solved the issue. 👍

**Comment by eppdev** [comment]
still need to remove oracle jdk with qt5-webkit-5.212.0alpha2-11

**Comment by AM-SL** [comment]
Still there is a issue.
Not fixed
Maintainer of `QT-Webkit` or `JDK` or `Zeal` should attention please
If not going to be fixed, port it to *GTK* is better and more elegant than *QT*.

**Comment by trollixx** [comment]
Per maintainer, Arch Linux does not support Oracle JDK, so there's nothing to fix. Definitely not from Zeal side.

I'll just keep this ticket open for a bit for people's awareness.

**Comment by monksy** [comment]
I'm seeing this with OpenJDK10 as well
