### ISSUE TITLE
Android docset render too slow

### ISSUE THREAD

**Issue by compilelife** [zealdocs/zeal#863]
I'm using zeal 0.5.0  in kubuntu 17.04.

I found zeal open some 'large' android class very slowly. (like AudioManager). Is it normal?

Time cost is depending on the doc file size. For example, AudioManager(356.4kb) take 10s while AudioManager.AudioPlaybackCallback(98.3kb) take less than 1s

Steps:
1. download android docset
2. type 'AudioManager' , select first one('AudioManager')
3. take about 10s or even longer to show
4. click 'open url' on top-right, take about 1s to show on browser
5. select 'AudioManager.AudioPlaybackCallback', take about 1s (or even faster) to show

**Comment by trollixx** [comment]
Which Qt WebKit version do you use? Can you try with [5.212](https://github.com/annulen/webkit)?

**Comment by compilelife** [comment]
I just download it from https://zealdocs.org/download.html#linux.

How can I find my qt webkit version?

From zeal menu 'help->about qt', see this: "This program uses Qt version 5.7.1."

**Comment by trollixx** [comment]
Yeah, then you are using the old Qt WebKit.

The only quick solution to get the new one, would be for me to finally package Zeal in one of these deploy-anywhere formats like AppImage or Snap.

**Comment by compilelife** [comment]
ok, I'll try.

**Comment by compilelife** [comment]
I think I've figure out why some page render so slow.

The 'slow pages' contain a link point to google, check [this](https://www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22search%22%2C%22version%22%3A%221.0%22%2C%22callback%22%3A%22__gcse.scb%22%2C%22style%22%3A%22https%3A%2F%2Fwww.google.com%2Fcse%2Fstatic%2Fstyle%2Flook%2Fv2%2Fdefault.css%22%2C%22language%22%3A%22en%22%7D%5D%7D).

Remove the link out of slow pages does greatly shorten the rendering time.

Unfortunately, chinese network disallow me to visit goolge website.

So, I suggest if you could:
1. Remove/Replace extenal links in docset (especially android docset) to make it pure offline
2. Or, set a short timeout to such links, when timeout reached, just skip it , and render the rest of page

**Comment by trollixx** [comment]
@compilelife An interesting finding! I want to add a pure offline mode to Zeal, which should address such issues.

But also docsets really shouldn't try to reach external resources. @Kapeli would it be possible to remove external references to Google from the Android docset?

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I'll fix it ASAP. Let me know if you notice it with any other docsets.

**Comment by Kapeli** [comment]
I've released a docset update that should fix this. Let me know if everything is ok.

**Comment by trollixx** [comment]
@compilelife Could you check if the updated docset properly works for you?

**Comment by compilelife** [comment]
@trollixx How can I get this updated docset ? Update 'the android docset' in zeal?

I'll try when I finish update the android docset (download android docset will be very very slow and unstable under my network)

By the way, could you make zeal workable when downloading or updating docsets (something like background download/update?

**Comment by compilelife** [comment]
@trollixx @Kapeli After update the latest android docset, this issue doesn't comes to me. Thanks.

**Comment by vgturtle127** [comment]
@trollixx I still get incredibly slow loading on the Android docset, and some other larger docsets. Is this pretty normal, or should they all load fairly quickly?

**Comment by trollixx** [comment]
@vgturtle127 In theory they should load quickly, but reasons for the slowness can be different. In this case it was pretty specific to external resources blocked by GFW.

**Comment by trollixx** [comment]
Resolving per above, please create new tickets if there's a problem.

**Comment by vgturtle127** [comment]
@trollixx Thanks, really appreciate it!
