### ISSUE TITLE
Zeal crashes on startup on Windows

### ISSUE THREAD

**Issue by jenisys** [zealdocs/zeal#889]
Platform: Windows7 (64-bit)

Problem occurs w/ portable Windows version (64-bit) and when I install via scoop.
After unpacking zeal into a new directory and starting it from there:

* The main windows opens up
* Shortly afterwards a message box opens with title: 

   ``A simple documentation browser. has stopped working``

  (with close-program or debug-program button option to leave the message box dialog)

**Comment by trollixx** [comment]
Do you have Microsoft Visual C++ 2015 Redistributable installed?

**Comment by jenisys** [comment]
No, Microsoft Visual C++ 2015 Redistributable is not installed.
And I cannot install it, because a newer version is installed (tells me the VC-REDIST installer).

**Comment by trollixx** [comment]
Strange. Do you see anything in system's event logs?

**Comment by jenisys** [comment]
Windows Application Event Log contains the following application error(s):

Faulting application name: zeal.exe, version: 0.5.0.0, timestamp: 0x5a35…
Faulting module name: Qt5Core.dll, version: 5.2.9.0, timestamp: 0x59d1...
Exception code: 0xc0000005
Fault offset: 0x000000…01e430a

NOTE: Qt5Core.dll from same directory as zeal.exe

**Comment by trollixx** [comment]
Sadly quite useless. I've seen a similar problem when MS VC++ redist was not installed, but that isn't your case.

Could you give the latest [CI build](https://bintray.com/zealdocs/windows-ci/zeal-portable-unstable) a try?

**Comment by jenisys** [comment]
I tried the zeal-portable x64 version 0.6.0-2 and 0.6.0.
Both work fine (but I have not tried much).
In both cases the Windows Event Log shows no problems w/ zeal.

Therefore, I assume the problem is fixed in this unstable version (soon to be released ;-)).

Thx,
Jens

**Comment by tserafim** [comment]
I am having the same problem.
I can't run any of the versions mentioned on this issue: 0.5.0, 0.6.0 and 0.6.0-2(both x64 and x86). The machine is running Windows 8.1Enterprise x64. I always see the Qt5Core.dll error message.
I have tried running Zeal with different versions of MS VC++ redist but had no luck. FYI, when I installed MS VC++ 2017 redist, MS VC++ 2015 was automatically uninstalled(according to the installed programs on Control Panel).

Ironically, I was able to run all of the x86 versions on a spare machine at home that runs Windows 8 x64... that does not have any MS VC++ redist installed(again, according to control panel). Go figure. Zeal x64 versions did not run, but it complained about a different dll.

On a more positive note, I run Zeal every day on a Fedora machine and I am really grateful for the work you do. Thanks a bunch!

Let me know if you need more information to debug this.

**Comment by trollixx** [comment]
I am not sure if there's anything special about Windows 8.1. Frankly nothing really changed between 0.5.0 and CI produced 0.6.0 in terms of libraries.

@tserafim Did you try both portable and non-portable versions? Do you have Qt SDK installed on your machine?

**Comment by trollixx** [comment]
The most common reason for this problem is missing [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53587).

So far no idea about those cases when redist is installed, and Zeal still doesn't start.

**Comment by tserafim** [comment]
@trollixx Yes, I tried portable and non-portable, x86 and x64 versions of 0.5.0 and 0.6.0.

Qt SDK is not installed.

Tried running some portable unstable 0.4.0 versions available on CI builds (0.4.0-30, 0.4.0-36) but got the Qt5Core.dll message.

The only version that runs is 0.4.0 x64 stable.

**Comment by trollixx** [comment]
@tserafim What does Windows event log say about the errors?

**Comment by tserafim** [comment]
@trollixx I just tried running 0.5.0 x64 portable version and 2 log events were generated, with different levels: error and information. 

The output is in Brazilian Portuguese but hopefully it uses a standard log format. Tell me if you need help with any words in particular.

Error log(I guess main information is ```faulty module name: Qt5Core.dll, version 5.9.2.0```)
```
Nome do aplicativo com falha: zeal.exe, versão: 0.5.0.0, carimbo de data/hora: 0x5a359a9b
Nome do módulo com falha: Qt5Core.dll, versão: 5.9.2.0, carimbo de data/hora: 0x59d1d4d2
Código de exceção: 0xc0000005
Deslocamento da falha: 0x00000000001e430a
ID do processo com falha: 0x330
Hora de início do aplicativo com falha: 0x01d3c05087309871
Caminho do aplicativo com falha: C:\Users\userName\zeal-portable-0.5.0-windows-x64\zeal.exe
Caminho do módulo com falha: C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5Core.dll
ID do Relatório: c61d1908-2c43-11e8-8332-eca86bef6a07
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha: 
```

Information log
```
Falha no bucket , tipo 0
Nome do Evento: APPCRASH
Resposta: Não disponível
ID do CAB: 0

Assinatura do problema:
P1: zeal.exe
P2: 0.5.0.0
P3: 5a359a9b
P4: Qt5Core.dll
P5: 5.9.2.0
P6: 59d1d4d2
P7: c0000005
P8: 00000000001e430a
P9: 
P10: 

Arquivos anexados:

Esses arquivos podem estar disponíveis em:
C:\Users\userName\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_zeal.exe_53effa2d3cfebb3a2cfc38f840ee41d4d30b6_ab1c0019_7cf4ab06

Símbolo da análise: 
Verificando novamente solução: 0
ID do Relatório: c61d1908-2c43-11e8-8332-eca86bef6a07
Status do Relatório: 2048
Bucket com hash:
```

The information log entry mentions a path where there might be some attached files. I found a ```report.wer``` file on that path and here is most of the content of that file. Note the exception code ```c0000005```
```
Version=1
EventType=APPCRASH
EventTime=131660266244589441
ReportType=2
Consent=1
...
NsAppName=zeal.exe
Response.type=4
Sig[0].Name=Nome do Aplicativo
Sig[0].Value=zeal.exe
Sig[1].Name=Versão do Aplicativo
Sig[1].Value=0.5.0.0
Sig[2].Name=Carimbo de Data//Hora do Aplicativo
Sig[2].Value=5a359a9b
Sig[3].Name=Nome do Módulo de Falhas
Sig[3].Value=Qt5Core.dll
Sig[4].Name=Versão do Módulo de Falhas
Sig[4].Value=5.9.2.0
Sig[5].Name=Carimbo de Data//Hora do Módulo de Falhas
Sig[5].Value=59d1d4d2
Sig[6].Name=Código de Exceção
Sig[6].Value=c0000005
Sig[7].Name=Deslocamento de Exceção
Sig[7].Value=00000000001e430a
...
UI[2]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\zeal.exe
UI[3]=A simple documentation browser. parou de funcionar
UI[4]=O Windows pode verificar online se há uma solução para o problema.
UI[5]=Procurar solução online e fechar o programa
UI[6]=Verificar online mais tarde se há uma solução e fechar o programa
UI[7]=Fechar o programa
LoadedModule[0]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\zeal.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\sqlite3.dll
LoadedModule[5]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5Concurrent.dll
LoadedModule[6]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5WebKitWidgets.dll
LoadedModule[7]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5Widgets.dll
LoadedModule[8]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5WebKit.dll
LoadedModule[9]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5Network.dll
LoadedModule[10]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5Gui.dll
LoadedModule[11]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\Qt5Core.dll
LoadedModule[12]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\archive.dll
LoadedModule[13]=C:\Windows\system32\USER32.dll
LoadedModule[14]=C:\Windows\SYSTEM32\VCRUNTIME140.dll
LoadedModule[15]=C:\Windows\SYSTEM32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[16]=C:\Windows\SYSTEM32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[17]=C:\Windows\SYSTEM32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[18]=C:\Windows\SYSTEM32\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[19]=C:\Windows\SYSTEM32\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[20]=C:\Windows\system32\SHELL32.dll
LoadedModule[21]=C:\Windows\SYSTEM32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[22]=C:\Windows\SYSTEM32\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[23]=C:\Windows\system32\GDI32.dll
LoadedModule[24]=C:\Windows\SYSTEM32\UxTheme.dll
LoadedModule[25]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[26]=C:\Windows\SYSTEM32\MSVCP140.dll
LoadedModule[27]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\icuuc57.dll
LoadedModule[28]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\icuin57.dll
LoadedModule[29]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[30]=C:\Windows\system32\WS2_32.dll
LoadedModule[31]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[32]=C:\Windows\SYSTEM32\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[33]=C:\Windows\SYSTEM32\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[34]=C:\Windows\SYSTEM32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[35]=C:\Windows\SYSTEM32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[36]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[37]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[38]=C:\Windows\system32\CRYPT32.dll
LoadedModule[39]=C:\Windows\system32\ole32.dll
LoadedModule[40]=C:\Windows\SYSTEM32\MPR.dll
LoadedModule[41]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[42]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\zlib1.dll
LoadedModule[43]=C:\Windows\system32\msvcrt.dll
LoadedModule[44]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[45]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[46]=C:\Windows\SYSTEM32\api-ms-win-crt-multibyte-l1-1-0.dll
LoadedModule[47]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\icudt57.dll
LoadedModule[48]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[49]=C:\Windows\system32\NSI.dll
LoadedModule[50]=C:\Windows\system32\RPCRT4.dll
LoadedModule[51]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[52]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[53]=C:\Windows\system32\MSASN1.dll
LoadedModule[54]=C:\Windows\SYSTEM32\ucrtbase.DLL
LoadedModule[55]=C:\Windows\SYSTEM32\cfgmgr32.dll
LoadedModule[56]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[57]=C:\Windows\system32\SspiCli.dll
LoadedModule[58]=C:\Windows\system32\IMM32.DLL
LoadedModule[59]=C:\Windows\system32\MSCTF.dll
LoadedModule[60]=C:\Windows\system32\tmumh\20019\AddOn\7.0.0.1142\TmUmEvt64.dll
LoadedModule[61]=C:\Windows\system32\PSAPI.DLL
LoadedModule[62]=C:\Windows\system32\tmumh\20019\TmMon\2.5.0.2070\tmmon64.dll
LoadedModule[63]=C:\Windows\SYSTEM32\shcore.dll
LoadedModule[64]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[65]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[66]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[67]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\platforms\qwindows.dll
LoadedModule[68]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[69]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[70]=C:\Windows\system32\userenv.dll
LoadedModule[71]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\imageformats\qico.dll
LoadedModule[72]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\imageformats\qgif.dll
LoadedModule[73]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\imageformats\qjpeg.dll
LoadedModule[74]=C:\Windows\system32\dwrite.dll
LoadedModule[75]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[76]=C:\Windows\system32\rsaenh.dll
LoadedModule[77]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[78]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\ssleay32.dll
LoadedModule[79]=C:\Users\userName\zeal-portable-0.5.0-windows-x64\LIBEAY32.dll
LoadedModule[80]=C:\Windows\SYSTEM32\api-ms-win-crt-conio-l1-1-0.dll
LoadedModule[81]=C:\Windows\system32\winhttp.dll
LoadedModule[82]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[83]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[84]=C:\Windows\system32\napinsp.dll
LoadedModule[85]=C:\Windows\system32\pnrpnsp.dll
LoadedModule[86]=C:\Windows\system32\NLAapi.dll
LoadedModule[87]=C:\Windows\System32\mswsock.dll
LoadedModule[88]=C:\Windows\System32\winrnr.dll
LoadedModule[89]=C:\Windows\System32\rasadhlp.dll
LoadedModule[90]=C:\Windows\System32\fwpuclnt.dll
FriendlyEventName=Parou de funcionar
ConsentKey=APPCRASH
AppName=A simple documentation browser.
AppPath=C:\Users\userName\zeal-portable-0.5.0-windows-x64\zeal.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=5199D6C968669824CA50517CEAAF033A
```

**Comment by trollixx** [comment]
@tserafim please try x64 build from [here](https://bintray.com/zealdocs/windows-ci/zeal-unstable/0.6.0-3-g30c85bb#files/zeal-unstable). It is now based on Qt 5.10.1.

**Comment by tserafim** [comment]
@trollixx I tried it but got same error

**Comment by trollixx** [comment]
I'll try checking Zeal on clean Windows installations, but that might take quite some time...

**Comment by henning-schild** [comment]
Depending on how you run cmake some internal libs might end up missing in the installed package, maybe #1085 helps on windows as well?

**Comment by milpita** [comment]
Similar error on windows10-1809-17763 when zeal-0.6.1 is installed for single user. Choosing system install (for all users) works now. Had to install VC++ Redist 2015.

**Comment by tianxingyang** [comment]
Similar error on windows10-2004-19041.113. I find this in Event Viewer
>Faulting application name: zeal.exe, version: 0.6.1.0, time stamp: 0x5bbc4535
Faulting module name: Qt5Network.dll, version: 5.11.1.0, time stamp: 0x5b234af4
Exception code: 0xc00000fd
Fault offset: 0x00000000000cd3c8
Faulting process id: 0x5e8
Faulting application start time: 0x01d5f4e91f61736a
Faulting application path: C:\Program Files\Zeal\zeal.exe
Faulting module path: C:\Program Files\Zeal\Qt5Network.dll
Report Id: 75ef0bfb-d34f-49fb-b80a-1f849b3d0557
Faulting package full name: 
Faulting package-relative application ID: 

Zeal works fine after I close my network proxy app. Why is this happening?

**Comment by trollixx** [comment]
@tianxingyang I don't think your error is related to this ticket, because it crashes in the Qt Network module. Is there an easy way to reproduce?

**Comment by hongwen000** [comment]
Save issue in windows 11 with proxy enabled.

**Comment by TheChilliPL** [comment]
Same error.

<details><summary>Event logs</summary>

**Error:**
```
Faulting application name: zeal.exe, version: 0.6.1.0, time stamp: 0x5bbc4535
Faulting module name: Qt5WebKit.dll, version: 0.0.0.0, time stamp: 0x5b7071f8
Exception code: 0xc0000005
Fault offset: 0x00000000002fcf3e
Faulting process id: 0x0x27C0
Faulting application start time: 0x0x1D8EAD4AE8964FE
Faulting application path: C:\Program Files\Zeal\zeal.exe
Faulting module path: C:\Program Files\Zeal\Qt5WebKit.dll
Report Id: 9c1529f1-59ce-4013-9cff-b9d0760d1f83
Faulting package full name: 
Faulting package-relative application ID: 
```
**Info:**
```
Fault bucket 2280487272769578736, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: zeal.exe
P2: 0.6.1.0
P3: 5bbc4535
P4: Qt5WebKit.dll
P5: 0.0.0.0
P6: 5b7071f8
P7: c0000005
P8: 00000000002fcf3e
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.178ed9b4-4639-4484-9a7f-54391788c561.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.08034639-403b-451b-8cfd-16d31f9b92f3.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220920_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.094ba4a3-12b3-4a03-b377-446b1f4cd6bd.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.dd226c63-5b50-4a2b-b35d-6103a03d3aa5.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.18fcacbd-3d10-4758-8351-43c2020cef7b.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.60265fcd-3325-4458-b2ea-2d045d91e592.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b2b20726-81e9-4b08-89f2-e2b239f4b40b.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_zeal.exe_ba38403e6c1c4034853582b3f84c2c7c5011d_01b35e99_e7c4176e-5c46-49d8-b50e-13cf1b6d87fe

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9c1529f1-59ce-4013-9cff-b9d0760d1f83
Report Status: 2147487744
Hashed bucket: 6e86736f07a735e04fa5eb17903ae6f0
Cab Guid: 0
```

</details>

[[ See `Report.wer` on Pastebin ]](https://pastebin.com/CX8SFEcx)

**Comment by trollixx** [comment]
Many different issues have been reported here. I suspect that significant portion of them came from the custom built Qt WebKit. Since migration to Qt WebEngine, this should no longer be an issue. Anyone can double check using [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yaml), and v0.7.0 will be tagged shortly.
